version: '3.8'

services:
  genealogic-tree-back:
    build: ./
    container_name: genealogic-tree-back
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001
    volumes:
      - ./app
      - /app/node_modules
    # command: npm install express cors body-parser


  db:
    image: postgres:13
    container_name: genealogic-tree-db
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:

    #  - POSTGRES_USER=gtree
     # - POSTGRES_PASSWORD=123PollitoIngles
      #- POSTGRES_DB=genealogicTree