version: '3.8'

services:
  genealogic-tree-back:
    build: ./
    image: genealogic-tree-back
    # container_name: genealogic-tree-back
    environment:
      - NODE_ENV=development
    ports:
      - 3001:3001

  genealogic-tree-load:
    build: ./
    image: genealogic-tree-back
    # container_name: genealogic-tree-load
    environment:
      - NODE_ENV=development
    command: npm run load

  db:
    image: postgres:13
    # container_name: genealogic-tree-db
    environment: 
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
