version: '3.8'

services:
  genealogic-tree-back:
    build: ./
    image: genealogic-tree-back
    depends_on:
      - db
    environment:
      - NODE_ENV=development
      - DEBUG=True
    ports:
      - 3001:3001
    volumes:
      - .:/app
    # command: npm install

  genealogic-tree-load:
    image: genealogic-tree-back
    depends_on:
      - genealogic-tree-back
    environment:
      - NODE_ENV=development
    volumes:
      - .:/app
    command: npm run load

  db:
    image: postgres:13
    environment: 
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydb
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
